import re
from datetime import datetime

from database import SessionLocal
from models import GeneratedOutput, PipelineRun, Project
from pipeline.state import PipelineState
from storage import get_storage


def _parse_given_when_then(criterion: str) -> tuple[str, str, str] | None:
    try:
        given_match = re.search(r"Given\s+(.+?)(?=\s+When\s+|\s+when\s+)", criterion, re.IGNORECASE)
        when_match = re.search(r"When\s+(.+?)(?=\s+Then\s+|\s+then\s+)", criterion, re.IGNORECASE)
        then_match = re.search(r"Then\s+(.+?)$", criterion, re.IGNORECASE)
        if given_match and when_match and then_match:
            return given_match.group(1).strip(), when_match.group(1).strip(), then_match.group(1).strip()
    except Exception:
        pass
    return None


def _format_criterion(criterion: str, index: int) -> str:
    parsed = _parse_given_when_then(criterion)
    if parsed:
        given, when, then = parsed
        return f"    Given {given}\n    When {when}\n    Then {then}"
    return f"    # TODO: reformat\n    # {criterion}"


def _build_bdd_markdown(framework: dict) -> str:
    today = datetime.utcnow().strftime("%B %d, %Y")
    lines = [f"# BDD User Stories\n\nGenerated by PM Pilot · {today}\n\n---\n"]

    for epic in framework.get("epics", []):
        lines.append(f"## Feature: {epic['title']}\n")
        lines.append(f"> {epic['description']}\n")

        for story in epic.get("user_stories", []):
            lines.append(f"### Scenario: {story['title']}\n")
            lines.append(f"**User Story:** {story['story']}\n")

            criteria = story.get("acceptance_criteria", [])
            if criteria:
                first = criteria[0]
                parsed = _parse_given_when_then(first)
                lines.append(f"```gherkin\nFeature: {epic['title']}\n")
                lines.append(f"  Scenario: {story['title']}")
                lines.append(f"    # Story: {story['story']}")
                if parsed:
                    given, when, then = parsed
                    lines.append(f"    Given {given}")
                    lines.append(f"    When {when}")
                    lines.append(f"    Then {then}")
                else:
                    lines.append(f"    # TODO: reformat")
                    lines.append(f"    # {first}")
                lines.append("```\n")

                if len(criteria) > 1:
                    lines.append("**Additional scenarios:**\n")
                    for criterion in criteria[1:]:
                        parsed = _parse_given_when_then(criterion)
                        lines.append("```gherkin")
                        if parsed:
                            given, when, then = parsed
                            lines.append(f"    Given {given}")
                            lines.append(f"    When {when}")
                            lines.append(f"    Then {then}")
                        else:
                            lines.append(f"    # TODO: reformat")
                            lines.append(f"    # {criterion}")
                        lines.append("```\n")

            lines.append(f"**Priority:** {story.get('priority', 'N/A')} | **Effort:** {story.get('effort', 'N/A')}\n")
            lines.append("---\n")

    return "\n".join(lines)


def bdd_node(state: PipelineState) -> PipelineState:
    db = SessionLocal()
    try:
        run = db.query(PipelineRun).filter_by(id=state["run_id"]).first()
        statuses = dict(run.stage_statuses)
        statuses["bdd"] = "running"
        run.stage_statuses = statuses
        run.current_stage = "bdd"
        db.commit()
    finally:
        db.close()

    try:
        bdd_markdown = _build_bdd_markdown(state["framework"])

        storage = get_storage()
        bdd_path = storage.save(state["project_id"], f"{state['run_id']}_bdd_stories.md", bdd_markdown)

        db = SessionLocal()
        try:
            run = db.query(PipelineRun).filter_by(id=state["run_id"]).first()
            output = GeneratedOutput(
                project_id=state["project_id"],
                run_id=state["run_id"],
                stage="bdd",
                content=bdd_markdown,
            )
            db.add(output)
            statuses = dict(run.stage_statuses)
            statuses["bdd"] = "complete"
            run.stage_statuses = statuses
            db.commit()
        finally:
            db.close()

        return {**state, "bdd_storage_path": bdd_path}

    except Exception as e:
        errors = list(state.get("errors", []))
        errors.append(f"BDD generation failed: {str(e)}")
        db = SessionLocal()
        try:
            run = db.query(PipelineRun).filter_by(id=state["run_id"]).first()
            project = db.query(Project).filter_by(id=state["project_id"]).first()
            statuses = dict(run.stage_statuses)
            statuses["bdd"] = "failed"
            run.stage_statuses = statuses
            run.current_stage = "failed"
            run.error = str(e)
            project.status = "failed"
            db.commit()
        finally:
            db.close()
        raise
